version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - /path/to/your/local/data:/data  # Bind mount for SQLite database
    command: python manage.py runserver 0.0.0.0:8000
